defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: automerge to the base branch with label automerge and branch protection passing
    conditions:
      # Pull requests targeting `main` branch that have `A:automerge` label
      - base=main
      - label=A:automerge
      # with 1 reviews and 0 changes requested left
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      # with the following workflows successful: 
      - check-success=add-issue-to-project
      - check-success=build-darwin-amd64
      - check-success=build-darwin-arm64
      - check-success=build-linux-amd64
      - check-success=build-linux-arm64
      - check-success=changelog-reminder
      - check-success=check-generated-protobuf
      - check-success=optimize-contract-rate-limiter
      - check-success=optimize-contract-crosschain-swaps
      - check-success=optimize-contract-swaprouter
      - check-success=optimize-contract-outpost
      - check-success=test-contract-rate-limiter
      - check-success=test-contract-crosschain-swaps
      - check-success=test-contract-swaprouter
      - check-success=test-contract-outpost
      - check-success=lint-contract-ibc-rate-limit
      - check-success=lint-contract-cosmwasm
      - check-success=lint-golangci
      - check-success=lint-documentation-linter
      - check-success=check-required-labels
      - check-success=run-simulation-tests
      - check-success=e2e
      - check-success=go-00
      - check-success=go-01
      - check-success=go-02
      - check-success=go-03
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
  - name: backport patches to v3.x branch
    conditions:
      - base=main
      - label=A:backport/v3.x
    actions:
      backport:
        branches:
          - v3.x
  - name: backport patches to v4.x branch
    conditions:
      - base=main
      - label=A:backport/v4.x
    actions:
      backport:
        branches:
          - v4.x
  - name: backport patches to v6.x branch
    conditions:
      - base=main
      - label=A:backport/v6.x
    actions:
      backport:
        branches:
          - v6.x
  - name: backport patches to v8.x branch
    conditions:
      - base=main
      - label=A:backport/v8.x
    actions:
      backport:
        branches:
          - v8.x
  - name: backport patches to v10.x branch
    conditions:
      - base=main
      - label=A:backport/v10.x
    actions:
      backport:
        branches:
          - v10.x
  - name: backport patches to v11.x branch
    conditions:
      - base=main
      - label=A:backport/v11.x
    actions:
      backport:
        branches:
          - v11.x
  - name: backport patches to v12.x branch
    conditions:
      - base=main
      - label=A:backport/v12.x
    actions:
      backport:
        branches:
          - v12.x
  - name: backport patches to v13.x branch
    conditions:
      - base=main
      - label=A:backport/v13.x
    actions:
      backport:
        branches:
          - v13.x
  - name: backport patches to v14.x branch
    conditions:
      - base=main
      - label=A:backport/v14.x
    actions:
      backport:
        branches:
          - v14.x
  - name: backport patches to v15.x branch
    conditions:
      - base=main
      - label=A:backport/v15.x
    actions:
      backport:
        branches:
          - v15.x
  - name: backport patches to v16.x branch
    conditions:
      - base=main
      - label=A:backport/v16.x
    actions:
      backport:
        branches:
          - v16.x
  - name: backport patches to v17.x branch
    conditions:
      - base=main
      - label=A:backport/v17.x
    actions:
      backport:
        branches:
          - v17.x
  - name: backport patches to v18.x branch
    conditions:
      - base=main
      - label=A:backport/v18.x
    actions:
      backport:
        branches:
          - v18.x
  - name: backport patches to v19.x branch
    conditions:
      - base=main
      - label=A:backport/v19.x
    actions:
      backport:
        branches:
          - v19.x
