# Changelog Reminder Workflow
#
# Ensures that a changelog entry is included in pull requests on the main branch.
# It checks for changes and verifies the presence of a changelog entry in the CHANGELOG.md file.
# If no entry is found, it adds a notification to remind the contributor.
#
# Triggers:
# - Triggered on any pull request events that targets the main branch
# 
# Required Secrets:
# - GITHUB_TOKEN: A token with repository access to commit the changelog reminder.

name: Changelog Reminder

on:
  pull_request:
    types: 
    - assigned
    - opened
    - synchronize
    - reopened
    - labeled
    - unlabeled
    branches:
      - main

jobs:

  changelog-reminder:
    name: changelog-reminder
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v4
      - 
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39.2.0
        with:
          files_ignore: |
            **/*.md
            **/*_test.go
            tests/**
            **/*.py
            .github/workflows/*.yml
      - 
        name: Changelog check
        # Skip this step and return success result for markdown only changes
        if: |
          steps.changed-files.outputs.any_changed == 'true' ||
          steps.changed-files.outputs.any_deleted == 'true' ||
          steps.changed-files.outputs.any_modified == 'true'
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: A:no-changelog
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
