# Check Broken Links Workflow
#
# This workflow runs on a schedule, specifically on the 1st and 15th days of every month at 10:00 UTC.
# It can also be manually triggered using the workflow_dispatch event.
# The purpose of this workflow is to check for broken links in Markdown and HTML files within the repository.
# If broken links are detected, it creates an issue with the details of the broken links.
#
# Triggers:
# - Schedule (1st and 15th days of every month at 10:00 UTC)
# - workflow_dispatch (manual triggering).
#
# Required Secrets:
# - GITHUB_TOKEN: A token with repository access to perform issue creation.

name: Check Broken Links

on:
  schedule:
    - cron: '0 10 1,15 * *' 
  workflow_dispatch:

jobs:
  check-broken-links:
    name: check-broken-links
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v4
      -
        name: Close Existing Broken Links Issue(s)
        uses: actions/stale@v8
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          # Broken link issues are automatically created with the "automated issue" and "Broken links" labels, so we only care about closing those.
          only-issue-labels: automated issue,Broken links
          ignore-issue-updates: true
          # close-issue-message requires permission `issues: write`
          close-issue-message: 'This issue is `stale` and has been closed due to a new "Check Broken Links" run. If any links are still broken, they will be reported in a new issue: https://github.com/osmosis-labs/osmosis/issues?q=is%3Aissue+is%3Aopen+label%3A%22automated+issue%22+label%3A%22Broken+links%22'
          days-before-issue-stale: 0
          days-before-issue-close: 0

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --exclude-loopback --verbose --no-progress './**/*.md' './**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Create Issue From File
        if: ${{ env.lychee_exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken Links Detected
          content-filepath: ./lychee/out.md
          labels: report, automated issue, Good first issue, Help wanted, Broken links
