# Check Required Labels Workflow
#
# The workflow ensures that the required labels are present on the pull request and returns a success result if they are.
# It ignores changes that only affect Markdown files (.md), test files (*_test.go), and workflow files (*.yml).
#
# Triggers:
# - pull_request:
#   - types: Triggered on the types 'opened', 'labeled', 'unlabeled', and 'synchronize'.
#   - branches: Triggered on the 'main' branch.

name: Check Required Labels

on:
  pull_request:
    types: 
      - opened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - "main"

jobs:
  check-required-labels:
    runs-on: ubuntu-latest
    name: check-required-labels
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v4
      - 
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39.2.0
        with:
          files_ignore: |
            **/*.md
            **/*_test.go
            tests/**
            **/*.py
            .github/workflows/*.yml
      - 
        name: Check required labels
        # Skip this step and return success result for markdown only changes
        if: |
          steps.changed-files.outputs.any_changed == 'true' ||
          steps.changed-files.outputs.any_deleted == 'true' ||
          steps.changed-files.outputs.any_modified == 'true'
        uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
        with: #Require one of the following labels
          mode: exactly
          count: 1
          labels: "V:state/breaking, V:state/compatible/no_backport, V:state/compatible/backport"
