# Verify that generated protobuf code is up-to-date.
#
# Note that we run these checks regardless whether the input files have
# changed, because generated code can change in response to toolchain updates
# even if no files in the repository are modified.

name: Check generated protobuf code
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  get_diff:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
      -
        name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            "proto/**"
            "**/**.proto"
            "**/**.pb.go"
            "**/**.sum"
            "**/client/**.go"
            "scripts/ci/**"
            "Makefile"
            "Dockerfile"
            ".github/workflows/check-generated.yml"
      -
        name: Set output
        id: vars
        run: echo "::set-output name=git_diff::$GIT_DIFF"
    outputs:
      git_diff: ${{ steps.vars.outputs.git_diff }}

  check-generated-protobuf:
    runs-on: ubuntu-latest
    needs: get_diff
    steps:
      - 
        uses: actions/checkout@v4
        if: needs.get_diff.outputs.git_diff
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      -
        name: "Check protobuf generated code"
        if: needs.get_diff.outputs.git_diff
        run: |
          make proto-all
          make run-querygen
      - 
        name: Commit changes
        if: needs.get_diff.outputs.git_diff
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.go
          git add *.proto
          git commit -m "Generated protofile changes" || echo "No changes to commit"
          git push
