# Lint Workflow
#
# This workflow runs various linters on the codebase to ensure code quality 
# and documentation compliance.
#
# Triggers:
# - pull_request: Triggered on pull requests.
# - push: Triggered on pushes to the main and concentrated-liquidity-main branches.
#
# Environment Variables:
# - GO_VERSION: Specifies the Go version to use for the golangci-lint job.
#
# Jobs:
# - golangci: Runs golangci-lint on the codebase.
# - documentation-linter: Runs a documentation linter on the codebase.

name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - concentrated-liquidity-main

env:
  GO_VERSION: '1.20.5'

jobs:
  golangci:
    name: lint-golangci
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
      -
        uses: technote-space/get-diff-action@v6.1.2
        with:
            PATTERNS: |
             **/**.go
             go.mod
             go.sum
             .github/**
             Makefile
      -
        name: 🐿 Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}

      -
        name: Run golangci-lint
        if: env.GIT_DIFF
        run: make lint

  documentation-linter:
    name: lint-documentation-linter
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`.
          fetch-depth: 0
      -
        name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.md
            go.mod
            go.sum
            Makefile
      -
        name: Run documentation linter
        if: env.GIT_DIFF
        run: make mdlint
